# Generated by Django 3.2.4 on 2024-07-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayixiaojin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.CharField(blank=True, max_length=100)),
                ('s2', models.CharField(blank=True, max_length=100)),
                ('s3', models.CharField(blank=True, max_length=100)),
                ('l1', models.CharField(blank=True, max_length=100)),
                ('l2', models.CharField(blank=True, max_length=100)),
                ('l3', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
