# Generated by Django 3.2.4 on 2024-07-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayixiaojin', '0002_publicannouncement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicAnnouncement',
        ),
        migrations.AddField(
            model_name='account',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='id_documents/'),
        ),
        migrations.AddField(
            model_name='account',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='id_documents/'),
        ),
    ]
